### ISSUE TITLE
Can't figure out how to predict sleep stages in the external test data once the training with the training data is complete.

### ISSUE THREAD

**Issue by vladimsv** [jshanna100/gssc#1]
Thank you for your software. We could not find a prediction function or facility for predicting external test data once the training is complete. Is there such a function?

**Comment by jshanna100** [comment]
Hi, thanks for your interest. Inference with the command line is documented in the readme.md. If you want to integrate inference into your own python code, consult the EEGInfer class in infer.py.

You mention "after training"; does that mean you have trained your own networks?

**Comment by vladimsv** [comment]
> Hi, thanks for your interest. Inference with the command line is documented in the readme.md. If you want to integrate inference into your own python code, consult the EEGInfer class in infer.py.
> 
> You mention "after training"; does that mean you have trained your own networks?

Thank you! Yes, we want to train the model using our data and use this trained model to predict our data too. We have thousands of PSG recordings and would like to compare your algorithms with some others.

**Comment by jshanna100** [comment]
Great! I would be curious to hear how it performs when you are done.

Bear in mind, that if you use custom nets, you will have to specify these to the EEGInfer instance, otherwise it will default to the built-in ones that I trained in the paper.
